# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/ComputerLogicDesign/MIPS/SingleCycleCPU/SingleCycleCPU.cache/wt [current_project]
set_property parent.project_path E:/ComputerLogicDesign/MIPS/SingleCycleCPU/SingleCycleCPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/ComputerLogicDesign/MIPS/SingleCycleCPU/SingleCycleCPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/ComputerLogicDesign/MIPS/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/ALU.v
  E:/ComputerLogicDesign/MIPS/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/ControlUnit.v
  E:/ComputerLogicDesign/MIPS/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/DataMemory.v
  E:/ComputerLogicDesign/MIPS/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/ImmediateExtend.v
  E:/ComputerLogicDesign/MIPS/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/InstructionMemory.v
  E:/ComputerLogicDesign/MIPS/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Mux2_32bits.v
  E:/ComputerLogicDesign/MIPS/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Mux4_32bits.v
  E:/ComputerLogicDesign/MIPS/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Mux4_32bitsPC.v
  E:/ComputerLogicDesign/MIPS/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Mux4_5bitsWReg.v
  E:/ComputerLogicDesign/MIPS/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/PC.v
  E:/ComputerLogicDesign/MIPS/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/RegisterFile.v
  E:/ComputerLogicDesign/MIPS/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/SingleCycleCPU.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top SingleCycleCPU -part xc7k70tfbv676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef SingleCycleCPU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file SingleCycleCPU_utilization_synth.rpt -pb SingleCycleCPU_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
